spring:
  #data:
    #redis:
      #host: localhost
      #port: 5672
      #password: 12345
      #ssl:
        #enabled: false
      #timeout: 5000             
      #lettuce:
        #pool:
          #max-idle: 20          
          #min-idle: 10
          #max-active: 100       
          #max-wait: 1000
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Methods Access-Control-Allow-Headers
      routes:
      - id: mock
        uri: https://jsonplaceholder.typicode.com
        predicates:
        - Path=/todos/1
        filters:
          - name: RequestRateLimiter
            args:
              '[redis-rate-limiter.requestedTokens]': 1
              '[redis-rate-limiter.replenishRate]': 1
              '[redis-rate-limiter.burstCapacity]': 1
              key-resolver: "#{@ipKeyResolver}"
